create table metric_medata (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_data date not null
);

create table day_notes (
  id integer NOT NULL,
  notes clob(15K),
);

create table weight_metrics (
  id integer NOT NULL,
  weight_pounds decimal(5,2) NOT NULL,
  weight_kilograms decimal(5,2) NOT NULL,
  FOREIGN KEY fk_wm_id metric_data(id)
);

create table blood_metrics (
  id integer NOT NULL,
  pressure varchar(32),
  pulse integer,
  FOREIGN KEY fk_bm_id metric_data(id)
);
