
create table weight_metrics (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_date date not null,
  weight_pounds decimal(5,2) not null,
  weight_kilograms decimal(5,2) not null
);

create table blood_metrics(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  metric_date date not null,
  pressure varchar(32),
  pulse integer
)
